declare var API_URL: string;
declare var PRODUCTION: boolean;
declare var DEVELOPMENT: boolean;
declare var INSTITUTION: string;
declare var SOURCE_URL: string;
declare var BUG_URL: string;
declare var SHOW_SUCCESS_MESSAGE: boolean;
declare var QUESTIONNAIRE_URL: string;
declare var SHOW_QUESTIONNAIRE_MESSAGE: boolean;
